services:
  - type: web
    name: bodily
    env: node
    buildCommand: pnpm install --frozen-lockfile && pnpm --filter @workspace/web run build && pnpm --filter @workspace/api-server run build
    startCommand: pnpm --filter @workspace/api-server run start
